apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.flaskApp.containerPort }}
      targetPort: {{ .Values.flaskApp.containerPort }}