apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: {{ .Values.flaskApp.containerPort }}
    targetPort: {{ .Values.flaskApp.containerPort }}
