apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - name: http
    protocol: TCP
    port: 80 
    targetPort: {{ .Values.flaskApp.containerPort }}
