name: Deploy to GKE

on:
    workflow_run:
      workflows: ["Docker Image CI"]
      types:
        - completed
      branches:
        - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: flask-gke-cluster
  GKE_REGION: us-central1
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy:
    name: Deploy Flask App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

      - name: Configure Kubernetes Access
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-gke-k8s/

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform-gke-k8s/

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: helm upgrade --install flask-app helm/