name: Deploy to GKE

on:
    workflow_run:
      workflows: ["Docker Image CI"]
      types:
        - completed
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init & Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
      env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials gke-cluster --region=us-central1 --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-app helm/ --namespace default
