name: CI/CD with Helm CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: yonihavasov/flask-app
  IMAGE_TAG: 0.0.${{ github.run_number }}

jobs:
  build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -t ${IMAGE_NAME}:latest flask-app
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${IMAGE_NAME}:latest

      - name: Test Locally with Docker Compose
        run: |
          docker compose up -d
          sleep 5
          curl -f http://localhost:5001

  deploy:
    runs-on: ubuntu-latest
    needs: build-Test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Google Cloud Service Account Key
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | base64 --decode > /tmp/key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json" >> $GITHUB_ENV

      - name: Install GKE Plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate with GKE
        run: |
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud container clusters get-credentials \
            ${{ secrets.GCP_CLUSTER_NAME }} \
            --project ${{ secrets.GCP_PROJECT_ID }} \

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Flask App Using Helm
        run: |
          helm upgrade --install flask-release charts/helm \
            --namespace default \
            --set flaskApp.tag=${IMAGE_TAG}

      - name: Debug Kubernetes Pods
        run: |
          kubectl get pods -A
          kubectl describe pods -n default
