name: helm ci

on:
    push:
      paths:
        - 'flask-app/charts/**'
      branches:
        - main
    pull_request:
      paths:
        - 'flask-app/charts/**'
      branches:
        - main

jobs:
    helm-chart-update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Helm
              run: |
                curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
                helm version

            - name: Update Helm Chart Version
              run: |
                cd flask-app/charts/helm
                sed -i "s/version: .*/version: 1.0.${{ github.run_number }}/g" ./Chart.yaml
                echo "# this file was modified by a ci to update helm version tagging" >> ./Chart.yaml

            - name: Package Helm Chart
              run: |
                cd flask-app/charts
                helm package helm --destination ..
                ls -lrta

            - name: Update Helm Repo Index # searches for tar.gz file in same dir.
              run: |
                helm repo index --url https://yonatanhavasov.github.io/helm-flaskgif .
                ls -lrta

            - name: Push helm chart ( tgz and index.yaml ) to helm repo
              env:
                HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }} 
              run: |
                set -x
                git clone https://${HELM_REPO_PAT}@github.com/yonatanhavasov/helm-flaskgif.git helmrepo
                cd helmrepo
                pwd

                git config --global user.name "github-actions-app"
                git config --global user.email "github-actions@gmail.com"
                ls -lrta

                rm -f *.tgz && rm -f index.yaml
                cp ../../*.tgz .
                cp ../index.yaml .
                ls -lrta

                git add .
                git commit -m "Updated helm chart version from APP REPO TRIGGER - Version 0.0.${{ github.run_number }}"
                git push origin main

                echo "pushed updated helm chart to helm-repo"


            
